server {
    listen 80;

    location / {
        proxy_pass http://penpot-frontend:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 0;

        # Auto-login: inject admin auth-token cookie
        proxy_set_header Cookie "auth-token=__PENPOT_AUTH_TOKEN__; $http_cookie";
    }
}
